id: P96EE1BBC
initial_creation_type: ocr
source_metadata:
  volumes:
    bca45af2a01044d388fa4a01feea94f1:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: སྡུད་པ་ཚིགས་སུ་བཅད་པའི་དཀའ་འགྲེལ།
      total_pages: 1426
      volume_number: 52
vol2fn:
  v052: v052.txt
